[tool.poetry]
name = "DHDRNet"
version = "0.1.0"
description = ""
authors = ["Shane Segal <shane@smsegal.ca>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.4.0"
torchvision = "^0.5.0"
networkx = "^2.4"
colour-science = {extras = ["optional"], version = "^0.3.14"}
colour-hdri = {extras = ["optional"], version = "^0.1.6"}
opencv-python = "^4.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.11.1"
pylama = "^7.7.1"
ipykernel = "^5.1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
