[tool.poetry]
name = "DHDRNet"
version = "0.1.0"
description = ""
authors = ["Shane Segal <shane@smsegal.ca>"]

[tool.poetry.dependencies]
python = "~3.8"
torch = "^1.5.0"
torchvision = "^0.6.0"
colour-hdri = {extras = ["optional"], version = "^0.1.6"}
opencv-python = "^4.1.2"
scikit-image = "^0.16.2"
more-itertools = "^8.2.0"
pillow = "^7.0.0"
tqdm = "^4.46.0"
pytorch-lightning = "^0.7.5"
pytorch-msssim = "^0.2.0"
recordclass = "^0.13.2"
pandas = "^1.0.4"
tables = "^3.6.1"
sewar = "^0.4.3"
perceptual-similarity-pytorch = {path = "../PerceptualSimilarity"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
matplotlib = "^3.1.3"
ipykernel = "^5.1.4"
isort = "^4.3.21"
pyflakes = "^2.1.1"
mypy = "^0.770"
ipympl = "^0.5.6"
seaborn = "^0.10.1"
pylama = "^7.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
